<?php echo lang('hi john doe', $new_account->getDisplayName()) ?>,<?php echo "\r\n"
?><?php echo "\r\n"
?><?php echo lang('user created your account', $new_account->getCreatedByDisplayName()) ?>.<?php echo "\r\n"
?><?php echo "\r\n"
?><?php echo "\r\n"
?><?php echo lang('visit and login', ROOT_URL) ?>:<?php echo "\r\n"
?><?php echo "\r\n"
?><?php echo lang('username') ?>: <?php echo $new_account->getUsername() ?><?php echo "\r\n"
?><?php echo "\r\n"
?> <?php echo lang('password') ?>: <?php echo $raw_password ?><?php echo "\r\n"
?><?php echo "\r\n"
?><?php echo "\r\n"
?>--<?php echo "\r\n"
?><?php echo ROOT_URL ?><?php echo "\r\n\r\n\r\n"
?>